### ISSUE TITLE
Feature request: Option to Remove Unhighlighted Posts

### ISSUE THREAD

**Issue by ulysseskan** [experimatt/hn-jobs-focus#1]
Nice extension, Matt!  I like your work better than the alternative frontends because I'm never sure if the alternative frontend missed a post.  The alt frontends also don't have the very newest posts.

Feature request: Allow people to remove unhighlighted posts from view.  For example, say you only want to see remote jobs.  Highlight "remote", press save, and everything else disappears.

This also makes for less scrolling.

Here's most of the code for `content.js` that does this:

```
const removeUnhighlightedComments = () => {
  const unhighlightedComments = document.querySelectorAll('tr.athing.comtr:not(.hn-ext-green-300-highlight)');
  unhighlightedComments.forEach((commentElement) => {
    commentElement.remove();
  });
}
```

I have this working in my local fork of the code (minus the UI toggle), so if this doesn't fit with your direction, ignore away.

**Comment by experimatt** [comment]
@ulysseskan great idea! Sorry I didn't see this right away - I've got to adjust my notification settings.

If you're able to throw up a PR for me to review and approve, that would be amazing.

**Comment by experimatt** [comment]
This was completed with https://github.com/experimatt/hn-jobs-focus/commit/c93a02ae4a64b87e705aa9e3b62918342b2d30a0
